# Configuración de compilación para Netlify
[build]
  command = "ng build --configuration production"
  publish = "dist/FrontendAE/browser"

# PRIMERO: Redirección específica para la ruta raíz
[[redirects]]
  from = "/"
  to = "/login"
  status = 301 # 301 indica una redirección permanente

# SEGUNDO: Regla general para que Angular maneje todas las demás rutas
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Reglas para el caché de los assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"